llvm/lib/Target/TVM/TVMISelLowering.cpp, llvm/lib/Target/TVM/TVMISelLowering.h
Code generation for [repro.ll.txt](https://github.com/tonlabs/TON-Compiler/files/3758714/repro.ll.txt) takes several minutes (562s on my machine) in debug mode and ~45s in release.
The change reduces the time to a fraction of second.
=> Fix lowering performance

llvm/lib/Target/TVM/TVMMachineInstrMatcher.h, llvm/lib/Target/TVM/TVMPeephole.cpp, llvm/test/CodeGen/TVM/optimizations/pushcont_inline.ll
This PR implements inlining of post-dominator basic block which is called by JMPX as a last instruction within both then/else basic blocks. So instead of JMPX to such block its instructions are moved after the IFELSE instruction.
=> Diamond basic block inlining for IFELSE

llvm/lib/Target/TVM/TVMISelDAGToDAG.cpp, llvm/test/CodeGen/TVM/call/calln.ll
It's the same logic as for CALL0/CALL1, just doing this manually for CALLN.
=> Unwrap CALLN's target address during ISel

Jenkinsfile
This PR disables windows build by default. We can add later a job for nightly builds which will trigger the job for master LLVM branch with BUILD_ON_WINDOWS=true parameter.
=> Disable windows build by default to improve CI speed

llvm/include/llvm/IR/IntrinsicsTVM.td
A dictionary is a cell, not a slice.
=> Fix dict primitives according to recent specification

stdlib/abi_parser.py
The serialization now looks the following
PUSHINT $calling_public_function_id$
PUSHINT 0x80000000
OR
CALL    $Serialize_Unsigned_Impl$
=> Fix serialization of an external message

llvm/lib/Target/TVM/TVMMCInstLower.cpp, llvm/test/CodeGen/TVM/logstr.ll, llvm/tools/clang/lib/CodeGen/CodeGenModule.cpp, llvm/tools/clang/test/CodeGen/tvm/string-literal.c, llvm/tools/llvm-mc-assemble-fuzzer/llvm-mc-assemble-fuzzer.cpp
A C input
```
char foo(int n) { return "bar"[n]; }
```
gets translated to
```
@.str = private constant [4 x i257] [i257 98, i257 97, i257 114, i257 0], align 1
define signext i257 @foo(i257 %n) {
entry:
%arrayidx = getelementptr inbounds [4 x i257], [4 x i257]* @.str, i257 0, i257 %n
%0 = load i257, i257* %arrayidx, align 1, !tbaa !2
ret i257 %0
}
```
=> Emit C string literals as [n x i257] constant arrays

llvm/lib/IR/Type.cpp, llvm/lib/Transforms/Scalar/SROA.cpp, llvm/tools/clang/lib/CodeGen/CGCall.cpp, llvm/tools/clang/test/CodeGen/tvm/test_union_with_bool.cpp
Fix for `func(union{ struct1, struct2,... } v)` union argument splitting.
Added `TVMUnionExpansion` type for union argument conversion into {i257, i257, ..., i257} args list.
Also added TVM types support in Type::getPrimitiveSizeInBits.
And fixed `* 8` cases in SROA (changed to `ByteSizeInBits`).
=> Split union argument fix and sroa bytesize corrections

llvm/include/llvm/CodeGen/AsmPrinter.h, llvm/lib/CodeGen/AsmPrinter/AsmPrinter.cpp, llvm/lib/IR/Type.cpp, llvm/lib/Target/TVM/TVMAsmPrinter.cpp, llvm/lib/Target/TVM/TVMFrameLowering.cpp, llvm/lib/Transforms/Scalar/SROA.cpp, llvm/tools/clang/include/clang/Basic/Attr.td, llvm/tools/clang/lib/AST/ItaniumMangle.cpp, llvm/tools/clang/lib/CodeGen/CGCall.cpp, llvm/tools/clang/lib/CodeGen/TargetInfo.cpp, llvm/tools/clang/lib/Sema/SemaDeclAttr.cpp, llvm/tools/clang/test/CodeGen/tvm/test_union_with_bool.cpp, stdlib/stdlib_cpp.tvm
Dependent from https://github.com/tonlabs/TON-Compiler/pull/36.
Added tvm_raw_func attribute.
For main_external, main_internal, main_ticktock, main_split, main_merge functions.
And for utility system functions.
Generates `.internal` for such functions in assembly.
And c++ mangling is not used for the functions.
=> Added tvm_raw_func attribute

llvm/lib/Target/TVM/TVMTargetMachine.cpp, llvm/test/CodeGen/TVM/tail-merge-bug.ll
The generic tail merging optimization (see lib/CodeGen/BranchFolding.cpp) is not aware of TVM control flow peculiarities and produces a broken output. This change disables it.
Fixes #52.
=> Disable tail merging

llvm/include/llvm/IR/IntrinsicsTVM.td, llvm/lib/Target/TVM/TVMInstrInfo.td, llvm/lib/Target/TVM/TVMStack.cpp, llvm/lib/Target/TVM/TVMStackFixup.cpp, llvm/lib/Target/TVM/TVMStackFixup.h, llvm/lib/Target/TVM/TVMStackModel.cpp, llvm/test/CodeGen/TVM/hiddenstack.ll, llvm/tools/clang/include/clang/Basic/BuiltinsTVM.def, stdlib/ton-sdk/smart-contract-info.c, stdlib/ton-sdk/smart-contract-info.h
When main_internal or main_external is called, contract and message
balances are located on stack. These values, however, are not accessible
in the stack model.
@llvm.tvm.hiddenstack(number) is to access values that resides in slots
that are not represented by stack model (e.g. hiddenstack(0) is the
contract balance, hiddenstack(2) is the incoming message balance).
=> Add intrinsic to access stack otherwise unavailable

llvm/tools/tvm-build/tvm-build.py
Linker produces public and private keys that might be needed to work
with the compiled contract.
=> Copy all files that linker produce to the output directory

llvm/lib/Target/TVM/TVMISelLowering.cpp, llvm/lib/Target/TVM/TVMInstrInfo.td, llvm/lib/Target/TVM/TVMStackPatterns.cpp, llvm/test/CodeGen/TVM/icmp.ll, llvm/test/CodeGen/TVM/select-isel.ll
Also fixed ppx (push, push, exchange) stack pattern problem, revealed by toolchain-test-suite/llvm/clang/gcc.c-torture/compile/20120927-1.c test.
=> Conditional select supported for tvm builtin types

llvm/lib/Target/TVM/TVMStack.cpp, llvm/lib/Target/TVM/TVMStack.h, llvm/lib/Target/TVM/TVMStackModel.cpp, llvm/lib/Transforms/IPO/DeadArgumentElimination.cpp, llvm/test/CodeGen/TVM/dead-arg-fix.ll, llvm/test/CodeGen/TVM/undef-cfg.ll, llvm/tools/clang/lib/AST/ExprConstant.cpp, llvm/tools/clang/lib/CodeGen/CodeGenFunction.cpp, llvm/tools/clang/lib/Lex/LiteralSupport.cpp, llvm/tools/clang/test/CodeGen/tvm/char-truncate.c, llvm/tools/clang/test/CodeGen/tvm/msg-address-intrinsics.cpp, llvm/tools/clang/test/CodeGen/tvm/ptr-cmp.c
Dependent from #73
Dependent from #71
=> Fix for dead arg elimination for tvm types - from upstream

llvm/tools/clang/include/clang/Sema/Sema.h, llvm/tools/clang/lib/Sema/SemaTemplateInstantiate.cpp, llvm/tools/clang/lib/Sema/SemaTemplateVariadic.cpp, llvm/tools/clang/lib/Sema/TreeTransform.h, llvm/tools/clang/test/CodeGen/tvm/pack-sizeof-for-struct.cpp
It is needed for generation of parsers/builders for message formats declared as structure.
=> sizeof...(T) returns struct fields count for struct template arguments

llvm/tools/tvm-build/CMakeLists.txt, llvm/tools/tvm-build/tvm-build.py
1. Copy tvm-build into cmake's binary directory.
2. Try to guess paths when invoked from there.
=> Make tvm-build usable from llvm build dir

package.sh
Package usage example:
```
$ tar xzf TON-Compiler-847e7869e81.tgz
$ cd sample ; ls
sample.c sample.abi
$ ~/TON-Compiler-847e7869e81/bin/abi_parser.py sample
$ ~/TON-Compiler-847e7869e81/bin/tvm-build \
--abi sample.abi \
sample.c sample_wrapper.c \
~/TON-Compiler-847e7869e81/stdlib/ton-sdk/*.c
Build succeeded.
```
=> Add packaging script

stdlib/ton-sdk/messages.c, stdlib/ton-sdk/messages.inc
Remove amount field from CommonMsgInfo
Fix src address serialization, according to https://github.com/ton-blockchain/ton/blob/master/crypto/block/transaction.cpp#L1440
it must be either addr_none (0b00) or the sender contract's address.
=> Fix internal outgoing message serialization

stdlib/abi_parser.py
The patch allows abi file name to be specified instead of the contract
name when generating C code with abi_parser.py tool.
=> Accept ABI file in abi_parser

stdlib/ton-sdk/tvm.h
Note that all examples are already moved to tvm_accept()
=> Remove ACCEPT macro from TON SDK for C

stdlib/cpp-sdk/tvm/replay_attack_protection/timestamp.hpp
The timestamp is in milliseconds while NOW return time in seconds.
=> Fix timestamp replay attack protection

llvm/tools/tvm-build/tvm-build++.py
This is required for toolchain-test-suite build, when includes and library dirs are different (`/usr/include` and `/usr/bin`).
=> Additional parameter in tvm-build++ - include directory for headers

stdlib/cpp-sdk/tvm/contract_handle.hpp
* Add explicit template parameters to fix type deduction issues.
* Add 10 000 000 nanogram as the default balance of outbound message for
a call (as Solidity does).
Note: the message balance is used to pay for calculations, so 0 implies
automatic abortion of a remote procedure call.
=> Fix contract_handle

llvm/lib/Target/TVM/TVMStackFixup.cpp, llvm/tools/clang/include/clang/AST/ASTContext.h, llvm/tools/clang/include/clang/Basic/Attr.td, llvm/tools/clang/include/clang/Basic/Builtins.h, llvm/tools/clang/lib/AST/ASTContext.cpp, llvm/tools/clang/lib/AST/DeclTemplate.cpp, llvm/tools/clang/lib/CodeGen/CodeGenTypes.cpp, llvm/tools/clang/lib/Sema/SemaDeclAttr.cpp, llvm/tools/clang/lib/Sema/SemaLookup.cpp, llvm/tools/clang/lib/Sema/SemaOverload.cpp, llvm/tools/clang/lib/Sema/SemaTemplate.cpp, llvm/tools/clang/test/CodeGen/tvm/dyn_chain_parser_test.cpp, llvm/tools/clang/test/CodeGen/tvm/struct_arg_big.c, llvm/tools/clang/test/CodeGen/tvm/test_union_with_bool.cpp, stdlib/cpp-sdk/tvm/chain_builder.hpp, stdlib/cpp-sdk/tvm/contract_handle.hpp, stdlib/cpp-sdk/tvm/error_code.hpp, stdlib/cpp-sdk/tvm/reflection.hpp, stdlib/cpp-sdk/tvm/schema/estimate_element.hpp, stdlib/cpp-sdk/tvm/schema/get_bitsize.hpp, stdlib/cpp-sdk/tvm/smart_switcher.hpp
* "noaccept" attribute
* __reflect_method_ptr_arg_struct to request method arguments structure by method ptr
* build_chain improvement to split internal expandable objects
* contract_handle::deploy_call
* _on_bounced method support for contract
* load_persistent_data / save_persistent_data as separate functions
* parse_chain_dynamic for correct arguments parsing (with cell wrapping)
=> Support for token contracts

stdlib/cpp-sdk/tvm/sequence.hpp, stdlib/cpp-sdk/tvm/smart_switcher.hpp
msg cell/slice and parsed int_sender/ext_sender stored into contract's fields if it is supported by contract (instead of parsed msg packed into global tuple).
=> Optimization of int_sender/ext_sender storage (in contract data)

llvm/tools/clang/lib/Driver/Driver.cpp, llvm/tools/clang/test/Driver/tvm-pipeline.cpp
-c -emit-llvm is the only valid case of using "assembler" for TVM.
=> Fix -c -emit-llvm handling in driver

cmake/Cache/ton-compiler.cmake, llvm/tools/clang/lib/Driver/Driver.cpp
If the compiler is built using cmake/Cache/ton-compiler.cmake, tvm is
going to be the default target.
Aside from that the patch removes information about the target and
theread model if the target is tvm.
=> Make TVM the default target in CMake cache file

cmake/Cache/ton-compiler.cmake, llvm/tools/clang/lib/Driver/ToolChains/Clang.cpp, llvm/tools/clang/lib/Driver/ToolChains/TVM.cpp, llvm/tools/clang/lib/Driver/ToolChains/TVM.h, llvm/tools/clang/test/CodeGen/tvm/string-literal.c, llvm/tools/clang/test/Driver/tvm-pipeline.cpp
* Make O3 default optimization level for TVM.
* Make default sysroot equal to install prefix (but the full path has to be
specified to utilize that feature).
* Enclose clang invocation to generate the abi into the pipeline.
* Make linker to generate what is specified in `-o` option.
Notes:
1. Clang invocation is a hacky way to generate the abi, it's probably
better to move it in llc.
2. The name for json file is <output stem>.json (a.json by default),
it changes if to specify `-o` option, but the tvc itself is named as the
linker decide to name it. A linker fix is coming soon.
3. Require 3211ca7041f2452e2e7c4e8080ce311ca80e2ebc commit in linker.
=> Pretify driver

llvm/tools/tvm-build/tvm-build.py
The option enables persistent data generation in c4 which C runtime relies on.
=> Add --language option for C contracts linkage

llvm/lib/Target/TVM/TVMStackModel.cpp, llvm/test/CodeGen/TVM/icmp.ll, llvm/test/CodeGen/TVM/reg_to_reg_copy.ll
If arguments are on stack in reverse order replace SGT with SLE, etc.
=> Optimize comparison

llvm/lib/Target/TVM/TVMStackFixup.cpp, llvm/projects/ton-compiler/cpp-sdk/tvm/contract_handle.hpp, llvm/projects/ton-compiler/cpp-sdk/tvm/dictionary.hpp, llvm/projects/ton-compiler/cpp-sdk/tvm/resumable.hpp, llvm/projects/ton-compiler/cpp-sdk/tvm/schema/basics.hpp, llvm/projects/ton-compiler/cpp-sdk/tvm/schema/make_builder.hpp, llvm/projects/ton-compiler/cpp-sdk/tvm/schema/make_parser.hpp, llvm/projects/ton-compiler/cpp-sdk/tvm/schema/parser/variant_parser.hpp, llvm/projects/ton-compiler/cpp-sdk/tvm/smart_switcher.hpp, llvm/tools/clang/include/clang/AST/ASTContext.h, llvm/tools/clang/include/clang/Basic/Builtins.h, llvm/tools/clang/lib/AST/ASTContext.cpp, llvm/tools/clang/lib/AST/DeclTemplate.cpp, llvm/tools/clang/lib/Driver/ToolChains/TVM.cpp, llvm/tools/clang/lib/Sema/SemaLookup.cpp, llvm/tools/clang/lib/Sema/SemaTemplate.cpp, llvm/tools/clang/test/CodeGen/tvm/test_call_proxy.cpp
Nice remote call syntax:
`bool_t finished = co_await handle(Grams(0)).checkFinished(answer_id);`
Instead of `co_await handle(Grams(0)).call<&Interface::checkFinished>(answer_id)` before.
=> Remote contract call proxy

llvm/projects/ton-compiler/cpp-sdk/tvm/chain_builder.hpp
Strange fix, but without it RootTokenContractNF constructor produces `error_code::non_single_refs_at_cell_wrap` exception.
Probably, codegen problem.
=> Temporary fix in dynamic chain parsing (Probably, codegen problems)

llvm/projects/ton-compiler/cpp-sdk/tvm/reflection.hpp, llvm/projects/ton-compiler/cpp-sdk/tvm/schema/json-abi-gen.hpp, llvm/projects/ton-compiler/cpp-sdk/tvm/smart_switcher.hpp, llvm/tools/clang/include/clang/AST/ASTContext.h, llvm/tools/clang/include/clang/Basic/Attr.td, llvm/tools/clang/include/clang/Basic/Builtins.h, llvm/tools/clang/lib/AST/ASTContext.cpp, llvm/tools/clang/lib/AST/DeclTemplate.cpp, llvm/tools/clang/lib/Sema/SemaDeclAttr.cpp, llvm/tools/clang/lib/Sema/SemaLookup.cpp, llvm/tools/clang/lib/Sema/SemaTemplate.cpp
implicit_func_id means that abi for this function will be generated without specified `"id" = `. And external answer id will have `(1 << 31)` bit set.
return_name("output_name") attribute means that single return function will have "output_name" specified in json abi for return value instead of default "value0".
Also supported squared attribute representations (like `[[external, internal]][[return_name("contexts")]]`).
=> implicit_func_id and return_name() attributes

llvm/projects/ton-compiler/cpp-sdk/tvm/chain_builder.hpp, llvm/projects/ton-compiler/cpp-sdk/tvm/chain_tuple.hpp, llvm/projects/ton-compiler/cpp-sdk/tvm/contract.hpp, llvm/projects/ton-compiler/cpp-sdk/tvm/debot.hpp, llvm/projects/ton-compiler/cpp-sdk/tvm/func_id.hpp, llvm/projects/ton-compiler/cpp-sdk/tvm/reflection.hpp, llvm/projects/ton-compiler/cpp-sdk/tvm/schema/json-abi-gen.hpp, llvm/projects/ton-compiler/cpp-sdk/tvm/schema/make_builder.hpp, llvm/projects/ton-compiler/cpp-sdk/tvm/smart_switcher.hpp, llvm/tools/clang/include/clang/AST/ASTContext.h, llvm/tools/clang/include/clang/Basic/Builtins.h, llvm/tools/clang/lib/AST/ASTContext.cpp, llvm/tools/clang/lib/AST/DeclTemplate.cpp, llvm/tools/clang/lib/Sema/SemaLookup.cpp, llvm/tools/clang/lib/Sema/SemaTemplate.cpp, llvm/tools/clang/test/CodeGen/tvm/hash_func_id.cpp
Now you may use implicit func ids (calculated as hash from function signature).
```
__interface [[no_pubkey]] ISMV_Debot {
[[external]]
void start();
}
```
Also added helper structs / constants for debots engine.
=> Calculated default hash func_ids

llvm/lib/Transforms/Coroutines/CoroFrame.cpp, llvm/lib/Transforms/Coroutines/CoroTVMExpand.cpp, llvm/lib/Transforms/Coroutines/TVMTypesSerialize.h, llvm/lib/Transforms/Scalar/SROA.cpp, llvm/projects/ton-compiler/cpp-sdk/tvm/Console.hpp, llvm/projects/ton-compiler/cpp-sdk/tvm/awaiting_responses_map.hpp, llvm/projects/ton-compiler/cpp-sdk/tvm/contract.hpp, llvm/projects/ton-compiler/cpp-sdk/tvm/contract_handle.hpp, llvm/projects/ton-compiler/cpp-sdk/tvm/error_code.hpp, llvm/projects/ton-compiler/cpp-sdk/tvm/globals.hpp, llvm/projects/ton-compiler/cpp-sdk/tvm/reflection.hpp, llvm/projects/ton-compiler/cpp-sdk/tvm/schema/abiv2.hpp, llvm/projects/ton-compiler/cpp-sdk/tvm/schema/json-abi-gen.hpp, llvm/projects/ton-compiler/cpp-sdk/tvm/smart_switcher.hpp, llvm/tools/clang/include/clang/AST/ASTContext.h, llvm/tools/clang/include/clang/Basic/Attr.td, llvm/tools/clang/include/clang/Basic/Builtins.h, llvm/tools/clang/lib/AST/ASTContext.cpp, llvm/tools/clang/lib/AST/DeclTemplate.cpp, llvm/tools/clang/lib/Sema/SemaDeclAttr.cpp, llvm/tools/clang/lib/Sema/SemaLookup.cpp, llvm/tools/clang/lib/Sema/SemaTemplate.cpp, llvm/tools/clang/test/CodeGen/tvm/Console_Debot.cpp, llvm/tools/clang/test/CodeGen/tvm/MultiBallot.hpp, llvm/tools/clang/test/CodeGen/tvm/MultisigWallet.hpp, llvm/tools/clang/test/CodeGen/tvm/SuperRoot.hpp
Depends on tonlabs/TON-Compiler#169
Added contract template class support for internal/external processing.
answer_id attribute for coroutines re-work.
=> Added contract template class support for internal/external processing.

llvm/lib/Target/TVM/TVMInstrInfo.td, llvm/lib/Target/TVM/TVMPeephole.cpp, llvm/test/CodeGen/TVM/call/calln.ll, llvm/test/CodeGen/TVM/semialias.ll, llvm/test/CodeGen/TVM/uint-cmp.ll
Replace stack manipulations with ROT, ROTREV, DROP2, DUP2, OVER2, TUCK where it
possible. Thus reduce gas cost by 8 gas per replacement.
=> Generate shorter form instruction where it's possible

llvm/projects/ton-compiler/cpp-sdk/tvm/contract.hpp, llvm/projects/ton-compiler/cpp-sdk/tvm/contract_handle.hpp, llvm/projects/ton-compiler/cpp-sdk/tvm/message_flags.hpp, llvm/projects/ton-compiler/cpp-sdk/tvm/schema/basics.hpp
tvm_rawreserve() as a simple proxy to __builtin_tvm_reserve().
handle.deploy_noop() to deploy contract with message body function id = 0.
=> tvm_rawreserve() and handle.deploy_noop() added

llvm/lib/Target/TVM/TVMPeephole.cpp, llvm/test/CodeGen/TVM/optimizations/blkpush.ll
Avoid generating BLKPUSH N, M where M > 15 which is illegal.
=> Fix blkpush optimization

llvm/lib/Target/TVM/TVMMoveMaterializable.cpp, llvm/lib/Target/TVM/TVMStoreCombine.cpp, llvm/test/CodeGen/TVM/optimizations/store-opt.ll
Two's compliment was calculated wrongly, the patch fixes it.
=> Fix store combine for negative constants

llvm/lib/Transforms/Coroutines/CoroFrame.cpp, llvm/lib/Transforms/Coroutines/CoroSplit.cpp, llvm/projects/ton-compiler/cpp-sdk/tvm/smart_switcher.hpp, llvm/tools/clang/include/clang/Serialization/ASTBitCodes.h, llvm/tools/clang/lib/Serialization/ASTReader.cpp, llvm/tools/clang/lib/Serialization/ASTWriter.cpp
to prevent values in wrong types at suspension points
=> Before coroutines split casts must be relocated close to their operand
