tonlabs/TON-Compiler

llvm/lib/Target/TVM/TVMStackFixup.cpp, llvm/lib/Target/TVM/TVMStackModel.cpp, llvm/test/CodeGen/TVM/undef-bug.ll, llvm/tools/clang/test/CodeGen/tvm/msg-address-intrinsics.cpp, llvm/tools/clang/test/CodeGen/tvm/runtime/triple_changes.c
Also fixed msg-address-intrinsics.cpp test, XFAIL'ed previously broken triple_changes.c test.
=> [#5] Fixed undef in single return and single argument instruction

llvm/lib/Target/TVM/TVMApplicationInstrInfo.td
=> Fix GETGLOB/SETGLOB definitions

llvm/lib/Target/TVM/TVMPeephole.cpp, llvm/lib/Target/TVM/TVMStackModel.cpp, llvm/test/CodeGen/TVM/unreachable.ll
This is another bugpoint-related fix.
=> Fix codegen failure in presence of unreachable

llvm/include/llvm/IR/IntrinsicsTVM.td, llvm/lib/Target/TVM/TVMDictionaryInstrInfo.td, llvm/test/CodeGen/TVM/allowance.ll, llvm/test/CodeGen/TVM/balanceof.ll, llvm/test/CodeGen/TVM/intrinsic.ll, llvm/test/CodeGen/TVM/load.ll, llvm/test/CodeGen/TVM/store.ll
This change includes #21 for the sake of CI.
=> Update load/store IR tests

stdlib/abi_parser.py
Remove outdated _authorized and signed attributes.
=> Update ABI parser to work with ABI v1

llvm/lib/Target/TVM/TVMMachineInstrMatcher.h, llvm/lib/Target/TVM/TVMPeephole.cpp, llvm/test/CodeGen/TVM/optimizations/ifelse.ll
Optimization of following pattern:
EQUAL
PUSHCONT {}
PUSHCONT {}
PUSHCONT {}
BLKSWAP	2, 4
SWAP
ROLL	2
ROLL	5
BLKSWAP	2, 4
SWAP
IFELSE
=> Additional ifelse case processing

llvm/tools/clang/lib/CodeGen/CodeGenModule.cpp, llvm/tools/clang/test/CodeGen/tvm/string-literal.c
Append enough zeros to fill a constant array entirely.
=> Fix a string literal bug

llvm/lib/Target/TVM/TVMStackFixup.cpp, llvm/lib/Target/TVM/TVMStackFixup.h, llvm/lib/Target/TVM/TVMStackModel.cpp, llvm/lib/Target/TVM/TVMStackPatterns.cpp, llvm/lib/Target/TVM/TVMStackPatterns.h, llvm/lib/Target/TVM/TVMStackVreg.h
The change is made automatically by `clang-format`
=> NFC: Reformat StackModel

llvm/lib/Target/TVM/TVMISelDAGToDAG.cpp, llvm/lib/Target/TVM/TVMISelLowering.cpp, llvm/lib/Target/TVM/TVMInstrInfo.td, llvm/lib/Target/TVM/TVMStackPatterns.cpp, llvm/test/CodeGen/TVM/call/calln.ll, llvm/test/CodeGen/TVM/icmp.ll, llvm/test/CodeGen/TVM/select-isel.ll
Dependent from https://github.com/tonlabs/TON-Compiler/pull/69
=> Fix for CALLN for tvm types

llvm/lib/Target/TVM/TVMStack.cpp, llvm/lib/Target/TVM/TVMStack.h, llvm/lib/Target/TVM/TVMStackModel.cpp, llvm/test/CodeGen/TVM/undef-cfg.ll
=> Additional fix for undef values processing

llvm/lib/Target/TVM/TVMStack.cpp, llvm/lib/Target/TVM/TVMStack.h, llvm/lib/Target/TVM/TVMStackModel.cpp, llvm/test/CodeGen/TVM/undef-cfg.ll, llvm/tools/clang/lib/AST/ExprConstant.cpp, llvm/tools/clang/lib/CodeGen/CodeGenFunction.cpp, llvm/tools/clang/lib/Lex/LiteralSupport.cpp, llvm/tools/clang/test/CodeGen/tvm/char-truncate.c, llvm/tools/clang/test/CodeGen/tvm/msg-address-intrinsics.cpp, llvm/tools/clang/test/CodeGen/tvm/ptr-cmp.c
=> 257-bit values fixes + typo

llvm/lib/Target/TVM/TVMStack.cpp, llvm/lib/Target/TVM/TVMStack.h, llvm/lib/Target/TVM/TVMStackModel.cpp, llvm/lib/Transforms/IPO/DeadArgumentElimination.cpp, llvm/test/CodeGen/TVM/dead-arg-fix.ll, llvm/test/CodeGen/TVM/undef-cfg.ll, llvm/tools/clang/include/clang/Basic/TargetInfo.h, llvm/tools/clang/lib/AST/ExprConstant.cpp, llvm/tools/clang/lib/Basic/Targets/TVM.cpp, llvm/tools/clang/lib/Basic/Targets/TVM.h, llvm/tools/clang/lib/CodeGen/CodeGenFunction.cpp, llvm/tools/clang/lib/Driver/CMakeLists.txt, llvm/tools/clang/lib/Driver/Driver.cpp, llvm/tools/clang/lib/Driver/ToolChains/TVM.cpp, llvm/tools/clang/lib/Driver/ToolChains/TVM.h, llvm/tools/clang/lib/Frontend/CompilerInvocation.cpp, llvm/tools/clang/lib/Lex/LiteralSupport.cpp, llvm/tools/clang/test/CodeGen/tvm/char-truncate.c, llvm/tools/clang/test/CodeGen/tvm/msg-address-intrinsics.cpp, llvm/tools/clang/test/CodeGen/tvm/ptr-cmp.c
Dependent from #74 
Dependent from #73
Dependent from #71
=> Clang fixes for tvm toolchain, c++17 enabled by default

llvm/include/llvm/CodeGen/AsmPrinter.h, llvm/include/llvm/CodeGen/MachineBasicBlock.h, llvm/include/llvm/CodeGen/TargetInstrInfo.h, llvm/lib/CodeGen/AsmPrinter/AsmPrinter.cpp, llvm/lib/CodeGen/BranchFolding.cpp, llvm/lib/CodeGen/MachineBasicBlock.cpp, llvm/lib/Target/TVM/CMakeLists.txt, llvm/lib/Target/TVM/TVM.h, llvm/lib/Target/TVM/TVMAsmPrinter.cpp, llvm/lib/Target/TVM/TVMContinuationsHoist.cpp, llvm/lib/Target/TVM/TVMControlFlowInstrInfo.td, llvm/lib/Target/TVM/TVMIfConversionTerm.cpp, llvm/lib/Target/TVM/TVMInstrInfo.cpp, llvm/lib/Target/TVM/TVMInstrInfo.h, llvm/lib/Target/TVM/TVMTargetMachine.cpp, llvm/test/CodeGen/TVM/cfg.ll, llvm/test/CodeGen/TVM/frameidx-copy.ll, llvm/test/CodeGen/TVM/intrinsic.ll, llvm/test/CodeGen/TVM/load.ll, llvm/test/CodeGen/TVM/optimizations/ifelse.ll, llvm/test/CodeGen/TVM/optimizations/pushcont_inline.ll, llvm/test/CodeGen/TVM/ret_nested.ll, llvm/test/CodeGen/TVM/undef-bug.ll, stdlib/ton-sdk/tvm.h
Moved into separate PR from https://github.com/tonlabs/TON-Compiler/pull/48.
Requires https://github.com/tonlabs/toolchain-test-suite/pull/31 PR to pass the tests.
=> AnalyzeBranch/InsertBranch/RemoveBranch supported. +THROWIF conversion.

llvm/include/llvm/Analysis/Utils/Local.h, llvm/lib/Transforms/Utils/SimplifyCFG.cpp, llvm/tools/clang/lib/Lex/LiteralSupport.cpp
=> Fix bugs found by UBSan

stdlib/ton-sdk/tvm.c, stdlib/ton-sdk/tvm.h
The plan is:
```
> 1. Introduce tvm_accept
2. Update tests
3. Remove ACCEPT()
```
=> Move from ACCEPT() to tvm_accept()

llvm/tools/clang/test/CodeGen/tvm/contract-handle-test.cpp, stdlib/cpp-sdk/tvm/contract_handle.hpp, stdlib/cpp-sdk/tvm/schema/basics.hpp, stdlib/cpp-sdk/tvm/schema/json-abi-gen.hpp
To call another contract functions (send messages):
```
contract_handle<IPiggybank>(addr).call<&IPiggybank::deposit>(10000);
```
=> Added contract_handle template for remote contract calls

llvm/lib/Target/TVM/TVMStackFixup.cpp, llvm/lib/Target/TVM/TVMStackModel.cpp, llvm/test/CodeGen/TVM/ret_nested.ll
Performance improvement:
Multisig/C++: 962385 -> 914867, diff -47518 or 5.2%
toolchain-test-suite: 415929 -> 403759, diff -12170 or 3.0%
Multisig/C perf drops down by 2.4%, but gets recovered by #131
=> Improve road pattern computation

llvm/include/llvm/ADT/Triple.h, llvm/tools/clang/include/clang/Basic/DiagnosticDriverKinds.td, llvm/tools/clang/lib/Driver/Driver.cpp, llvm/tools/clang/lib/Driver/ToolChain.cpp, llvm/tools/clang/lib/Driver/ToolChains/TVM.cpp, llvm/tools/clang/lib/Driver/ToolChains/TVM.h, llvm/tools/clang/test/Driver/tvm-pipeline.cpp
* Remove assembly and ignore -c option.
* Change default linker to tvm_linker.
=> Fix default tvm pipeline

llvm/tools/clang/lib/Driver/Driver.cpp, llvm/tools/clang/lib/Driver/ToolChains/TVM.cpp, llvm/tools/clang/lib/Driver/ToolChains/TVM.h, llvm/tools/clang/test/CodeGen/tvm/setcode.c, llvm/tools/clang/test/Driver/tvm-pipeline.cpp
Implement functionality of tvm-build++ in clang driver.
=> Add LTO pipeline to clang driver

README.md
* Remove example of usage section to avoid repletion of information given
in samples repository.
* Update building guide and provide options to speed it up and hints how
to troubleshoot out of memory issues.
=> Update README to reflect the recent changes in Clang for TVM

llvm/tools/clang/lib/Driver/Driver.cpp, llvm/tools/clang/test/Driver-TVM/tvm-pipeline.cpp
Claim arguments passed to -Wl / -XLinker.
=> Claim linker arguments

llvm/projects/ton-compiler/cpp-sdk/tvm/resumable.hpp, llvm/projects/ton-compiler/cpp-sdk/tvm/schema/basics.hpp, llvm/projects/ton-compiler/cpp-sdk/tvm/schema/make_parser.hpp, llvm/projects/ton-compiler/cpp-sdk/tvm/schema/parser/variant_parser.hpp, llvm/projects/ton-compiler/cpp-sdk/tvm/smart_switcher.hpp
Fix for `resumable<void>` coroutines
=> Fix for parse optional<T> in persistent data

llvm/projects/ton-compiler/cpp-sdk/tvm/reflection.hpp, llvm/projects/ton-compiler/cpp-sdk/tvm/schema/json-abi-gen.hpp, llvm/projects/ton-compiler/cpp-sdk/tvm/sequence.hpp, llvm/projects/ton-compiler/cpp-sdk/tvm/smart_switcher.hpp, llvm/tools/clang/include/clang/AST/ASTContext.h, llvm/tools/clang/include/clang/Basic/Attr.td, llvm/tools/clang/include/clang/Basic/Builtins.h, llvm/tools/clang/lib/AST/ASTContext.cpp, llvm/tools/clang/lib/AST/DeclTemplate.cpp, llvm/tools/clang/lib/Sema/SemaDeclAttr.cpp, llvm/tools/clang/lib/Sema/SemaLookup.cpp, llvm/tools/clang/lib/Sema/SemaTemplate.cpp, llvm/tools/clang/test/CodeGen/tvm/BigStringTest.cpp
Dependent on https://github.com/tonlabs/TON-Compiler/pull/160
Constant string will be packed into cells using stu256 for big parts and lesser stu for the rest of bytes in cell
=> Optimized packing of big strings into cells

llvm/include/llvm/IR/IntrinsicsTVM.td, llvm/lib/Target/TVM/TVMApplicationInstrInfo.td, llvm/test/CodeGen/TVM/intrinsic.ll, llvm/tools/clang/include/clang/Basic/BuiltinsTVM.def
Add builtin + intrinsic to produce it.
=> Add CDATASIZE instruction

llvm/lib/Target/TVM/CMakeLists.txt, llvm/lib/Target/TVM/TVM.h, llvm/lib/Target/TVM/TVMDefineUndef.cpp, llvm/lib/Target/TVM/TVMTargetMachine.cpp, llvm/test/CodeGen/TVM/deebot.ll, llvm/test/CodeGen/TVM/undef-bug.ll
The pass is to define undef i257, cell and slice in STU, STI, STREF and
STSLICE instructions, thus prevent a codegen issue.
=> Add DefineUndef pass

llvm/lib/Target/TVM/TVMInstrFormats.td, llvm/lib/Target/TVM/TVMInstrInfo.td, llvm/test/CodeGen/TVM/icmp.ll
Introduce selection patterns for them.
=> Add EQINT, NEQINE, GTINT, LESSINT

llvm/lib/Target/TVM/TVMStackFixup.cpp, llvm/lib/Target/TVM/TVMStackFixup.h
Add logic which analyse if there possibility to blkdrop elements when
cleaning up the stack.
=> Remove blocks of elements when cleaning up

llvm/lib/Transforms/Coroutines/CoroFrame.cpp, llvm/lib/Transforms/Coroutines/TVMTypesSerialize.h, llvm/projects/ton-compiler/cpp-sdk/tvm/Console.hpp, llvm/projects/ton-compiler/cpp-sdk/tvm/contract_handle.hpp, llvm/projects/ton-compiler/cpp-sdk/tvm/sequence.hpp, llvm/projects/ton-compiler/cpp-sdk/tvm/smart_switcher.hpp
Console interface fixes as a result of tonos-cli cpp debots testing.
=> Debot console interface fixes

llvm/projects/ton-compiler/cpp-sdk/tvm/dict_map.hpp, llvm/projects/ton-compiler/cpp-sdk/tvm/log_sequence.hpp, llvm/projects/ton-compiler/cpp-sdk/tvm/schema/json-abi-gen.hpp, llvm/projects/ton-compiler/cpp-sdk/tvm/schema/message.hpp, llvm/projects/ton-compiler/cpp-sdk/tvm/smart_switcher.hpp
* answer_id=0 for requests from non-coroutines
* dict_map fix for small/big elements
*  abi-gen fix for nested structs and signature hash calculation
=> log_sequence and fixes

llvm/projects/ton-compiler/cpp-sdk/tvm/smart_switcher.hpp, llvm/tools/clang/include/clang/Serialization/ASTBitCodes.h, llvm/tools/clang/lib/Serialization/ASTReader.cpp, llvm/tools/clang/lib/Serialization/ASTWriter.cpp
Dependent on https://github.com/tonlabs/TON-Compiler/pull/185
=> Fix for same function names problem (Proposal/SuperRoot contestApproved example)
